### ISSUE TITLE
Groups rather than individual accounts

### ISSUE THREAD

**Issue by jecosgrove** [baloise/digital-signature#12]
Hello,
I've been testing out this signature macro for use in Confluence.  Really nice.  I was wondering if there is a way to add functionality for adding active directory groups rather than just individual accounts?  I have a large group of users that I'd like to have sign a confluence document, but do not want the manual process of adding them one by one.

**Comment by culmat** [comment]
Hi there,
we could use confluence groups, which in term can be [mapped to external directories](https://confluence.atlassian.com/doc/connecting-to-an-ldap-directory-229838241.html).
Not sure what to do about the display of the "missing signatures". That could be a really big list.
Also it could change dynamically with the group, so  not sure how interesting it would be to display those ...?
Regards
Matthias

**Comment by jecosgrove** [comment]
Hi Matthias,
Thanks for responding.  Yes, if there is a way to use confluence groups that would be very helpful.  It could then pull membership from security groups in AD.  Changing dynamically is actually what I'd want.  I'm using this module to sign participation in a training course.

**Comment by ahomarsilicongears** [comment]
Hi Matthias,

We really like your add-on to keep a registry of who read each documentation. It would be really convenient for us too to be able to define signers by groups.

Thanks in advance.

**Comment by culmat** [comment]
Hi, 
I will give this feature a try. Just to let you know. It will probably not be in September. 
Regards

**Comment by mcameron001** [comment]
Hi!

I would love this functionality. Were you able to progress this issue any further?

Cameron

**Comment by culmat** [comment]
Hi all,
i made an implementation - t is in release 0.9.2 together with more features and fixes.
We are aware #19 is becoming more and more important. It is next on the list.
Please be aware this has impact on performance with large groups. Consider using maxSigners.
Also there is no group chooser, so you might prefer to protected the entire page and use the inheritance feature. If you protect the page you can also enter * as group name so that anybody who can see the page can sign. This disables the calculation of missing signatures and should also work with big groups.

Looking forward to your feed back.
Regards
Matthias
