### ISSUE TITLE
Email button broken?

### ISSUE THREAD

**Issue by culmat** [baloise/digital-signature#13]
Email button seems to be broken?

**Comment by seawyk** [comment]
hi. Is the email button fixed? i installed 0.9.3 and clicking on the email button shows a mailto link like the one below

mailto:Lionel%20Seaw%3Cseawyk@xxx.com%3E?Subject=Document+Review

Is this correct and by design? Are there any plans to automate the email process to automatically send a mail to all signers? or to inform signers by creating this as a task?
