### ISSUE TITLE
Data migration can cause loss of signatures given?

### ISSUE THREAD

**Issue by reginvaldr** [baloise/digital-signature#33]
We use Confluence Server. We recently migrated from Confluence to Confluence using a data migration. We have detected that some pages lost their signatures that were already given. Do you know what can cause this doing a data migration. Do you know what to do to prevent this happening

**Comment by MarkusTiede** [comment]
Hi @reginvaldr - thanks reporting this!

Can you give a bit more details what data migration means for you?

The signature is built from the [pageId, title and body](https://github.com/baloise/digital-signature/blob/master/src/main/java/com/baloise/confluence/digitalsignature/Signature.java#L31) - did any of these attributes change on migration?

**Comment by reginvaldr** [comment]
We did an XML import from one database to another. Both Postgresql with
same version. After the import we saw only the first version of the page
where three versions were expected. We didn't find anything in the log but
the digital signature was used as macro (as only one). Also the content in
the digital signature was gone from the page. So between source and target
lost two versions and the signatures that were present before export and
import.
We are using 6.1.2 Confluence and 0.10.3 digital-signature. We are
interested what could have caused it to prevent it next time.

Grt Ronald

Op di 30 okt. 2018 10:08 schreef Markus Tiede <notifications@github.com>:

**Comment by culmat** [comment]
Hi Ronald,

the signatures are stored outside the containing page in [Bandana](https://developer.atlassian.com/server/confluence/what-is-bandana-one-form-of-confluence-persistence/). This allows us to ensure that the contract has not been modified, while the page itself (and thus the contract meta information contained in the macro) can still be edited. 

There is some more discussion on this in [Issue1](https://github.com/baloise/digital-signature/issues/1#issuecomment-315024906 ).

It is required to also copy the Bandana storage in order to preserve signatures during migration. ( Not sure how to do this, please check Atlassian documentation)

Best regards
Matthias
